services:

  vsav_fe_dev:
    container_name: vsav_fe_dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - 'matchdb-web:/app'
    ports:
      - 9000:9000
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  matchdb-web:
    driver: local