import { P1_CHAR_DEFAULT, P2_CHAR_DEFAULT, TYPE_DEFAULT, URL_DEFAULT, WINNING_CHAR_DEFAULT } from "@Pages/addmatch/components/FormDefaults.const"

export const SEARCH_TYPE_NAMES = {
  BY_URL : "URL",
  BY_MU : "MATCHUP"
}

const SEARCH_FORM_BY_URL = {
  ...TYPE_DEFAULT,
  ...URL_DEFAULT
}
const SEARCH_FORM_BY_MU = {
  ...P1_CHAR_DEFAULT,
  ...P2_CHAR_DEFAULT,
  ...WINNING_CHAR_DEFAULT
}

export const SEARCH_FORM_STATE = {
  [SEARCH_TYPE_NAMES.BY_URL] : SEARCH_FORM_BY_URL,
  [SEARCH_TYPE_NAMES.BY_MU]  : SEARCH_FORM_BY_MU
}
