export enum CharNamesEnum {
  AN = "AN",
  AU = "AU",
  BI = "BI",
  BU = "BU",
  DE = "DE",
  FE = "FE",
  GA = "GA",
  JE = "JE",
  LE = "LE",
  LI = "LI",
  MO = "MO",
  SA = "SA",
  VI = "VI",
  QB = "QB",
  ZA = "ZA",
}

export const CharShortNameToFullName:Record<string, string> = {
  ["AN"] : "Anakaris",
  ["AU"] : "Aulbath",
  ["BI"] : "Bishamon",
  ["BU"] : "Bulleta",
  ["DE"] : "Demitri",
  ["FE"] : "Felicia",
  ["GA"] : "Gallon",
  ["JE"] : "Jedah",
  ["LE"] : "Lei-Lei",
  ["LI"] : "Lillith",
  ["MO"] : "Morrigan",
  ["SA"] : "Sasquatch",
  ["VI"] : "Victor",
  ["QB"] : "Q-Bee",
  ["ZA"] : "Zabel",
}
export type CharShortName = keyof typeof CharShortNameToFullName
export type CharFullName = keyof typeof CharFullNameToShortName

export const CharFullNameToShortName:Record<string, string> = {
  ["Anakaris" ] : "AN",
  ["Aulbath"  ] : "AU",
  ["Bishamon" ] : "BI",
  ["Bulleta"  ] : "BU",
  ["Demitri"  ] : "DE",
  ["Felicia"  ] : "FE",
  ["Gallon"   ] : "GA",
  ["Jedah"    ] : "JE",
  ["Lei-Lei"  ] : "LE",
  ["Lillith"  ] : "LI",
  ["Morrigan" ] : "MO",
  ["Sasquatch"] : "SA",
  ["Victor"   ] : "VI",
  ["Q-Bee"    ] : "QB",
  ["Zabel"    ] : "ZA",
}
export const CharNamesEnumDisplay: { [index: string]: string } = {
  [CharNamesEnum.AN] : "Anakaris",
  [CharNamesEnum.AU] : "Aulbath",
  [CharNamesEnum.BI] : "Bishamon",
  [CharNamesEnum.BU] : "Bulleta",
  [CharNamesEnum.DE] : "Demitri",
  [CharNamesEnum.FE] : "Felicia",
  [CharNamesEnum.GA] : "Gallon",
  [CharNamesEnum.JE] : "Jedah",
  [CharNamesEnum.LE] : "Lei-Lei",
  [CharNamesEnum.LI] : "Lillith",
  [CharNamesEnum.MO] : "Morrigan",
  [CharNamesEnum.SA] : "Sasquatch",
  [CharNamesEnum.VI] : "Victor",
  [CharNamesEnum.QB] : "Q-Bee",
  [CharNamesEnum.ZA] : "Zabel",
};
